### PR TITLE
Use prefixTemplate even if nameTemplate is not defined

### LINKED ISSUE #141: prefixTemplate is ignored if nameTemplate is not specified
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I specified prefixTemplate in both the global section and definitions section and it appears to be ignored.  Alarms are still prefixed with the stack name.  If nameTemplate is specified, then the value is used.

* What did you expect should have happened?
The value of prefixTemplate changes my alarm names despite nameTemplate not being specified.

* What was the config you used?
```
custom:
  prune:
    automatic: true
    number: 5
  pythonRequirements:
    dockerizePip: non-linux
    layer:
      compatibleRuntimes:
        - python3.8
  alerts:
    prefixTemplate: my-prefix-${{self:provider.stage}}
    definitions:
      SQSErrorAlarm:
        prefixTemplate: my-prefix-${{self:provider.stage}}
         ...
```

* What stacktrace or error message from your provider did you see?
N/A

Similar or dependent issues:
* N/A

## Additional Data

* ***Serverless Framework Version***: 2.3.0
* ***Plugin Version***: 1.6.1
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

### PR DESCRIPTION
**Pull request by Marcholio**
## What did you implement:

Closes #141 

## How did you implement it:

If nameTemplate is undefined and prefixTemplate is defined, use a default format of `${prefixTemplate}-$[functionName]-$[metricName]`

## How can we verify it:

1. Add updated plugin version as a dependency to the example project: `yarn add -D Marcholio/serverless-plugin-aws-alerts#fix/prefixTemplate`
2. Run dryRun deployment of the example project `sls deploy --stage staging --noDeploy`
3. Note that configured alerts do not contain `AlarmName` property
4. Add `prefixTemplate: my-prefix-${opt:stage}` to alert configuration. Do not define nameTemplate.
5. Run dryRun deployment
6. Note that the alerts have `AlarmName` property with value matching the defined default format.
7. Define different prefix for one function, eg.
```yaml
functions:
  foo:
    handler: foo.handler
    alarms: # merged with function alarms
      - customAlarm
      - name: fooAlarm
        .....
        prefixTemplate: other-prefix
```
8. Run dry run deployment
9. Verify that foo function has `AlarmName` property with "other-prefix" as a prefix.

## Todos:

- [X] Write tests
- [X] Write documentation
- [X] Fix linting errors
- [X] Provide verification config/commands/resources

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -227,7 +227,7 @@ class AlertsPlugin {
       };
     } else {
       throw new Error(
-        `Missing type for alarm ${alarm.name} on function ${functionName}, must be one of 'static' or 'anomalyDetection'`
+        `Missing type for alarm ${definition.name} on function ${functionName}, must be one of 'static' or 'anomalyDetection'`
```
Comment (Marcholio) [inline src/index.js:230]: I also changed this to `definition.name` because I think that there was a mistake. If all previous ifs are false and we end up here, `alarm` should be undefined and therefore using `alarm.name` probably results in a "Can't read property name of undefined" error?
